name: Build GNAT cross compiler Docker images

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-src:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_write }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/src/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gnat-cross-src:community-2021
  build-arm-eabi:
    environment: build
    runs-on: ubuntu-latest
    needs: build-src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_write }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/gnat/Dockerfile
          push: true
          build-args: |
            target=arm-eabi
            registry=ghcr.io/${{ github.repository_owner }}/
          tags: ghcr.io/${{ github.repository_owner }}/gnat-cross-arm-eabi:community-2021
  build-msp430-elf:
    environment: build
    runs-on: ubuntu-latest
    needs: build-src
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_write }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/gnat/Dockerfile
          push: true
          build-args: |
            target=msp430-elf
            registry=ghcr.io/${{ github.repository_owner }}/
          tags: ghcr.io/${{ github.repository_owner }}/gnat-cross-msp430-elf:community-2021
